# Auto-generated seed data source

# 1. Biomass Properties
BIOMASS_PROPERTIES_DATA = [
    {'biomass_name': 'Resíduo de Pinus', 'pci_mj_kg': 18.8, 'combustion_emission': 0.0},
    {'biomass_name': 'Resíduo de Eucaliptus', 'pci_mj_kg': 15.8, 'combustion_emission': 0.0},
    {'biomass_name': 'Carvão vegetal de eucalipto', 'pci_mj_kg': 15.8, 'combustion_emission': 0.0},
    {'biomass_name': 'Casca de Amendoin', 'pci_mj_kg': 17.1, 'combustion_emission': 0.0},
    {'biomass_name': 'Eucaliptus Virgem', 'pci_mj_kg': 15.8, 'combustion_emission': 0.0},
    {'biomass_name': 'Pinus Virgem', 'pci_mj_kg': 18.8, 'combustion_emission': 0.0},
]

# 2. MUT Allocations
BIOMASS_MUT_ALLOCATION_DATA = [
    {'biomass_name': 'Resíduo de Pinus', 'lifecycle_stage': 'Resíduos de galhos e folhas', 'product_name': 'Tora de madeira', 'allocation_product': 0.675, 'coproduct_name': 'Resíduos de galhos e folhas', 'allocation_coproduct': 0.325},
    {'biomass_name': 'Resíduo de Pinus', 'lifecycle_stage': 'Resíduos de Casca ', 'product_name': 'Troncos descascados', 'allocation_product': 0.6075, 'coproduct_name': 'Casca de pinus', 'allocation_coproduct': 0.0675},
    {'biomass_name': 'Resíduo de Pinus', 'lifecycle_stage': 'Resíduo de serragem', 'product_name': 'Madeira serrada', 'allocation_product': 0.30375, 'coproduct_name': 'Subproduto da serraria', 'allocation_coproduct': 0.30375},
    {'biomass_name': 'Resíduo de Pinus', 'lifecycle_stage': 'Não especificado', 'product_name': '-', 'allocation_product': 0.0, 'coproduct_name': 'Não especificado', 'allocation_coproduct': 0.0},
    {'biomass_name': 'Resíduo de Eucaliptus', 'lifecycle_stage': 'Resíduos de galhos e folhas', 'product_name': 'Tora de madeira', 'allocation_product': 0.675, 'coproduct_name': 'Resíduos de galhos e folhas', 'allocation_coproduct': 0.325},
    {'biomass_name': 'Resíduo de Eucaliptus', 'lifecycle_stage': 'Resíduos de Casca ', 'product_name': 'Troncos descascados', 'allocation_product': 0.6075, 'coproduct_name': 'Casca de eucalipto', 'allocation_coproduct': 0.0675},
    {'biomass_name': 'Resíduo de Eucaliptus', 'lifecycle_stage': 'Resíduo de serragem', 'product_name': 'Madeira serrada', 'allocation_product': 0.30375, 'coproduct_name': 'Subproduto da serraria', 'allocation_coproduct': 0.30375},
    {'biomass_name': 'Resíduo de Eucaliptus', 'lifecycle_stage': 'Não especificado', 'product_name': '-', 'allocation_product': 0.0, 'coproduct_name': 'Não especificado', 'allocation_coproduct': 0.0},
    {'biomass_name': 'Carvão vegetal de eucalipto', 'lifecycle_stage': 'Não aplica', 'product_name': 'Carvão vegetal', 'allocation_product': 1.0, 'coproduct_name': '-', 'allocation_coproduct': 0.0},
    {'biomass_name': 'Casca de Amendoin', 'lifecycle_stage': 'Não aplica', 'product_name': 'Amendoim', 'allocation_product': 0.77, 'coproduct_name': 'Casca de amendoim', 'allocation_coproduct': 0.23},
    {'biomass_name': 'Eucaliptus Virgem', 'lifecycle_stage': 'Não aplica', 'product_name': 'Eucaliptus virgem', 'allocation_product': 0.675, 'coproduct_name': 'Resíduo de eucaliptus', 'allocation_coproduct': 0.325},
    {'biomass_name': 'Pinus Virgem', 'lifecycle_stage': 'Não aplica', 'product_name': 'Pinus virgm', 'allocation_product': 0.675, 'coproduct_name': 'Resíduo de pinus', 'allocation_coproduct': 0.325},
]

# 3. MUT Factors
MUT_FACTORS_DATA = [
    {'state': 'Acre', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Acre', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Acre', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Alagoas', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Alagoas', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Alagoas', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Amapá', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Amapá', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Amapá', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Amazonas', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Amazonas', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Amazonas', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Bahia', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Bahia', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Bahia', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Ceará', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Ceará', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Ceará', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Distrito Federal', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Distrito Federal', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Distrito Federal', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Espírito Santo', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Espírito Santo', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Espírito Santo', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Goiás', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Goiás', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Goiás', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Maranhão', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Maranhão', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Maranhão', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Mato Grosso', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Mato Grosso', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Mato Grosso', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Mato Grosso do Sul', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Mato Grosso do Sul', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Mato Grosso do Sul', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Minas Gerais', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Minas Gerais', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Minas Gerais', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Pará', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Pará', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Pará', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Paraíba', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Paraíba', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Paraíba', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Paraná', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Paraná', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Paraná', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Pernambuco', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Pernambuco', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Pernambuco', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Piauí', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Piauí', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Piauí', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Rio de Janeiro', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Rio de Janeiro', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Rio de Janeiro', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Rio Grande do Norte', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Rio Grande do Norte', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Rio Grande do Norte', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Rio Grande do Sul', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Rio Grande do Sul', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Rio Grande do Sul', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Rondônia', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Rondônia', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Rondônia', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Roraima', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Roraima', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Roraima', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Santa Catarina', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Santa Catarina', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Santa Catarina', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'São Paulo', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'São Paulo', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'São Paulo', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Sergipe', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Sergipe', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Sergipe', 'culture': 'Amendoim', 'emission_factor': 0.0},
    {'state': 'Tocantins', 'culture': 'Pinus', 'emission_factor': 0.0},
    {'state': 'Tocantins', 'culture': 'Eucalipto', 'emission_factor': 0.0},
    {'state': 'Tocantins', 'culture': 'Amendoim', 'emission_factor': 0.0},
]

# 4. Biomass Production Emissions
BIOMASS_PRODUCTION_DATA = [
    {'biomass_name': 'Resíduo de Pinus', 'emission_factor': 0.0250947158128894, 'allocation_product': 0.0, 'allocation_coproduct': 1.0, 'biomass_type': 'Pinus'},
    {'biomass_name': 'Resíduo de Eucaliptus', 'emission_factor': 0.0250947158128894, 'allocation_product': 0.0, 'allocation_coproduct': 1.0, 'biomass_type': 'Eucalipto'},
    {'biomass_name': 'Carvão vegetal de eucalipto', 'emission_factor': 1.76253630637048, 'allocation_product': 1.0, 'allocation_coproduct': 0.0, 'biomass_type': 'Eucalipto'},
    {'biomass_name': 'Casca de Amendoin', 'emission_factor': 0.666051667404622, 'allocation_product': 0.77, 'allocation_coproduct': 0.23, 'biomass_type': 'Amendoin'},
    {'biomass_name': 'Eucaliptus Virgem', 'emission_factor': 0.1037211616932195, 'allocation_product': 1.0, 'allocation_coproduct': 0.0, 'biomass_type': 'Eucalipto'},
    {'biomass_name': 'Pinus Virgem', 'emission_factor': 0.42172914039108, 'allocation_product': 1.0, 'allocation_coproduct': 0.0, 'biomass_type': 'Pinus'},
    {'biomass_name': 'Amido de milho', 'emission_factor': 1.20067098542324, 'allocation_product': 1.0, 'allocation_coproduct': 0.0, 'biomass_type': '-'},
]

# 5. Industrial Inputs (Production Scope 3)
INDUSTRIAL_INPUTS_DATA = [
    {'input_name': 'Eletricidade da rede - mix média voltagem', 'input_type': 'electricity', 'emission_factor': 0.50231323962, 'unit': 'kWh'},
    {'input_name': 'Eletricidade da rede - mix alta voltagem', 'input_type': 'electricity', 'emission_factor': 0.128769234, 'unit': 'kWh'},
    {'input_name': 'Diesel', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Gás Natural', 'input_type': 'fuel', 'emission_factor': 0.3345, 'unit': 'Nm³'},
    {'input_name': 'GLP', 'input_type': 'fuel', 'emission_factor': 0.72196735612, 'unit': 'kg'},
    {'input_name': 'Gasolina A', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Etanol anidro', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Etanol hidratado', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Cavaco de madeira', 'input_type': 'fuel', 'emission_factor': 0.36469999999999997, 'unit': 'kg'},
    {'input_name': 'Lenha', 'input_type': 'fuel', 'emission_factor': 0.026, 'unit': 'kg'},
    {'input_name': 'Combustão de Diesel', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Uso de Gás Natural', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'Nm³'},
    {'input_name': 'Uso de GLP', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'kg'},
    {'input_name': 'Combustão de Gasolina A', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Combustão de Etanol anidro', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Combustão de Etanol hidratado', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'litro'},
    {'input_name': 'Combustão de Cavaco de madeira', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'kg'},
    {'input_name': 'Combustão de Lenha', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'kg'},
    {'input_name': 'Insumos industriais', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'None'},
    {'input_name': 'Água', 'input_type': 'fuel', 'emission_factor': 2.3749708800000002e-05, 'unit': 'litro'},
    {'input_name': 'Óleo lubrificante', 'input_type': 'fuel', 'emission_factor': 1.5124000000000002, 'unit': 'kg'},
    {'input_name': 'Areia de sílica', 'input_type': 'fuel', 'emission_factor': 0.0357757137501474, 'unit': 'kg'},
    {'input_name': 'Transporte', 'input_type': 'fuel', 'emission_factor': 0.0, 'unit': 'None'},
    {'input_name': 'Transporte, caminhão 7.5-16t', 'input_type': 'fuel', 'emission_factor': 0.09369746796799999, 'unit': 'tkm'},
    {'input_name': 'Transporte caminhão 16-32t', 'input_type': 'fuel', 'emission_factor': 0.098020519375, 'unit': 'tkm'},
    {'input_name': 'Transporte, caminhão  >32t', 'input_type': 'fuel', 'emission_factor': 0.061124489876, 'unit': 'tkm'},
    {'input_name': 'Transporte, caminhão  60m³', 'input_type': 'fuel', 'emission_factor': 0.061124489876, 'unit': 'tkm'},
    {'input_name': 'Transporte, navio', 'input_type': 'fuel', 'emission_factor': 0.00951832926726, 'unit': 'tkm'},
    {'input_name': 'Combustão do Pellet de resíduo de Pinus', 'input_type': 'other', 'emission_factor': 0.0, 'unit': 'Kg'},
    {'input_name': 'Combustão do Pellet de resíduo de Eucalipto', 'input_type': 'other', 'emission_factor': 0.0, 'unit': 'Kg'},
    {'input_name': 'Combustão do Pellet de resíduo de amendoin', 'input_type': 'other', 'emission_factor': 0.0, 'unit': 'Kg'},
]

# 6. Stationary Combustion (Scope 1)
STATIONARY_COMBUSTION_DATA = [
    {'fuel_name': 'Casca de amendoin', 'unit': 'kg base seca', 'co2_fossil': 0.0, 'co2_biogenic': 0.0, 'ch4_fossil': 0.0, 'ch4_biogenic': 1.4e-05, 'n2o_emission': 2.2e-05, 'co2_eq_emission': 0.0},
    {'fuel_name': 'Cavacos de madeira', 'unit': 'kg base seca', 'co2_fossil': 0.0, 'co2_biogenic': 0.0, 'ch4_fossil': 0.0, 'ch4_biogenic': 1.4e-05, 'n2o_emission': 2.2e-05, 'co2_eq_emission': 0.0},
    {'fuel_name': 'Lenha', 'unit': 'kg base seca', 'co2_fossil': 0.0, 'co2_biogenic': 0.0, 'ch4_fossil': 0.0, 'ch4_biogenic': 1.4e-05, 'n2o_emission': 2.2e-05, 'co2_eq_emission': 0.0},
    {'fuel_name': 'Resíduos florestais', 'unit': 'kg base seca', 'co2_fossil': 0.0, 'co2_biogenic': 0.0, 'ch4_fossil': 0.0, 'ch4_biogenic': 1.4e-05, 'n2o_emission': 2.2e-05, 'co2_eq_emission': 0.0},
    {'fuel_name': 'Gás combustível renovável', 'unit': 'MJ', 'co2_fossil': 0.0, 'co2_biogenic': 0.055, 'ch4_fossil': 0.0, 'ch4_biogenic': 1e-06, 'n2o_emission': 0.0, 'co2_eq_emission': 0.0001},
    {'fuel_name': 'Gás Natural', 'unit': 'MJ', 'co2_fossil': 0.056100000000000004, 'co2_biogenic': 0.0, 'ch4_fossil': 5e-06, 'ch4_biogenic': 0.0, 'n2o_emission': 0.0, 'co2_eq_emission': 0.056299999999999996},
    {'fuel_name': 'Gás Natural', 'unit': 'kg', 'co2_fossil': 2.067, 'co2_biogenic': 0.0, 'ch4_fossil': 0.000184, 'ch4_biogenic': 0.0, 'n2o_emission': 4e-06, 'co2_eq_emission': 2.0734},
    {'fuel_name': 'GLP', 'unit': 'MJ', 'co2_fossil': 0.0631, 'co2_biogenic': 0.0, 'ch4_fossil': 2e-06, 'ch4_biogenic': 0.0, 'n2o_emission': 0.0, 'co2_eq_emission': 0.0632},
    {'fuel_name': 'GLP', 'unit': 'kg', 'co2_fossil': 2.932, 'co2_biogenic': 0.0, 'ch4_fossil': 7.000000000000001e-05, 'ch4_biogenic': 0.0, 'n2o_emission': 5e-06, 'co2_eq_emission': 2.9358},
    {'fuel_name': 'Carvão de coque', 'unit': 'MJ', 'co2_fossil': 0.095, 'co2_biogenic': 0.0, 'ch4_fossil': 0.0003, 'ch4_biogenic': 0.0, 'n2o_emission': 2e-06, 'co2_eq_emission': 0.1039},
    {'fuel_name': 'Diesel A (B0)', 'unit': 'kg', 'co2_fossil': 3.134, 'co2_biogenic': 0.0, 'ch4_fossil': 0.000127, 'ch4_biogenic': 0.0, 'n2o_emission': 2.5e-05, 'co2_eq_emission': 3.1443000000000003},
    {'fuel_name': 'Biodiesel (B100)', 'unit': 'kg', 'co2_fossil': 0.0, 'co2_biogenic': 2.763, 'ch4_fossil': 0.0, 'ch4_biogenic': 0.000127, 'n2o_emission': 2.5e-05, 'co2_eq_emission': 0.0103},
    {'fuel_name': 'Óleo combustível', 'unit': 'MJ', 'co2_fossil': 0.077, 'co2_biogenic': 0.0, 'ch4_fossil': 3e-06, 'ch4_biogenic': 0.0, 'n2o_emission': 1e-06, 'co2_eq_emission': 0.0777},
    {'fuel_name': 'Óleo combustível', 'unit': 'kg', 'co2_fossil': 3.108, 'co2_biogenic': 0.0, 'ch4_fossil': 0.00011999999999999999, 'ch4_biogenic': 0.0, 'n2o_emission': 2.4e-05, 'co2_eq_emission': 3.1179},
    {'fuel_name': 'Etanol anidro', 'unit': 'MJ', 'co2_fossil': 0.0, 'co2_biogenic': 0.08, 'ch4_fossil': 0.0, 'ch4_biogenic': 3e-06, 'n2o_emission': 1e-06, 'co2_eq_emission': 0.0002},
    {'fuel_name': 'Etanol anidro', 'unit': 'kg', 'co2_fossil': 0.0, 'co2_biogenic': 2.25, 'ch4_fossil': 0.0, 'ch4_biogenic': 8.5e-05, 'n2o_emission': 1.7e-05, 'co2_eq_emission': 0.006900000000000001},
    {'fuel_name': 'Etanol hidratado', 'unit': 'MJ', 'co2_fossil': 0.0, 'co2_biogenic': 0.08, 'ch4_fossil': 0.0, 'ch4_biogenic': 3e-06, 'n2o_emission': 1e-06, 'co2_eq_emission': 0.0002},
    {'fuel_name': 'Etanol hidratado', 'unit': 'kg', 'co2_fossil': 0.0, 'co2_biogenic': 2.1, 'ch4_fossil': 0.0, 'ch4_biogenic': 7.9e-05, 'n2o_emission': 1.6e-05, 'co2_eq_emission': 0.0065},
]

